# VS Codeの黄色い波線を消してスッキリさせる設定
include: package:flutter_lints/flutter.yaml

linter:
  rules:
    # 「constを付けなさい」という警告を無効化
    prefer_const_constructors: false
    prefer_const_literals_to_create_immutables: false
    prefer_const_declarations: false
    
    # クラス作成時の「Keyが必要」という警告を無効化
    use_key_in_widget_constructors: false
    
    # 「print文を使わないで」という警告を無効化
    avoid_print: false
    
    # その他、よく出る細かい注意をオフにする
    library_private_types_in_public_api: false
    use_build_context_synchronously: false